### PR TITLE
Drop privileged mode. Use CAP_SYS_RESOURCE to allow ulimit -l

### PR DESCRIPTION
**Pull request by hikhvar**

### CODE REVIEW

**Comment by pires** [comment]
@hikhvar can you please show me logs of this running, as I don't have the bandwidth to test it right now?

**Comment by hikhvar** [comment]
The Logs:
```
(git)-[master] % kubectl logs es-data-2407596567-3cg31
[2017-02-28T07:38:04,390][INFO ][o.e.n.Node               ] [] initializing ...
[2017-02-28T07:38:05,193][INFO ][o.e.e.NodeEnvironment    ] [i-_yoLv] using [1] data paths, mounts [[/data (/dev/sda1)]], net usable_space [92.2gb], net total_space [94.3gb], spins? [possibly], types [ext4]
[2017-02-28T07:38:05,203][INFO ][o.e.e.NodeEnvironment    ] [i-_yoLv] heap size [247.6mb], compressed ordinary object pointers [true]
[2017-02-28T07:38:05,213][INFO ][o.e.n.Node               ] node name [i-_yoLv] derived from node ID [i-_yoLvMSVaHujedgNmd2A]; set [node.name] to override
[2017-02-28T07:38:05,253][INFO ][o.e.n.Node               ] version[5.2.0], pid[11], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/4.4.21+/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111/25.111-b14]
[2017-02-28T07:38:13,544][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [aggs-matrix-stats]
[2017-02-28T07:38:13,545][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [ingest-common]
[2017-02-28T07:38:13,546][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [lang-expression]
[2017-02-28T07:38:13,546][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [lang-groovy]
[2017-02-28T07:38:13,551][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [lang-mustache]
[2017-02-28T07:38:13,551][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [lang-painless]
[2017-02-28T07:38:13,553][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [percolator]
[2017-02-28T07:38:13,553][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [reindex]
[2017-02-28T07:38:13,553][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [transport-netty3]
[2017-02-28T07:38:13,553][INFO ][o.e.p.PluginsService     ] [i-_yoLv] loaded module [transport-netty4]
[2017-02-28T07:38:13,554][INFO ][o.e.p.PluginsService     ] [i-_yoLv] no plugins loaded
[2017-02-28T07:38:14,782][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
[2017-02-28T07:38:33,846][INFO ][o.e.n.Node               ] initialized
[2017-02-28T07:38:33,847][INFO ][o.e.n.Node               ] [i-_yoLv] starting ...
[2017-02-28T07:38:34,720][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 87:7d:7c:1c:ea:6e:c9:fc
[2017-02-28T07:38:35,203][INFO ][o.e.t.TransportService   ] [i-_yoLv] publish_address {10.64.2.17:9300}, bound_addresses {10.64.2.17:9300}
[2017-02-28T07:38:35,282][INFO ][o.e.b.BootstrapChecks    ] [i-_yoLv] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-02-28T07:38:36,863][INFO ][o.e.m.j.JvmGcMonitorService] [i-_yoLv] [gc][3] overhead, spent [278ms] collecting in the last [1s]
[2017-02-28T07:38:38,954][INFO ][o.e.c.s.ClusterService   ] [i-_yoLv] detected_master {AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300}, added {{AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300},{OCJHvDC}{OCJHvDCxRcKpokVz68tRxA}{aqYcLIhYRQ6p8pi_xosytA}{10.64.0.15}{10.64.0.15:9300},{TzRctcO}{TzRctcOYSQOUj3KH2UExow}{i2oK1n6PRs-9TiKGD67DRg}{10.64.2.16}{10.64.2.16:9300},{9W1kcRS}{9W1kcRSpTVOmAXH9DdmJYg}{IOq3jET5Rb2kGksgBd9OUw}{10.64.1.7}{10.64.1.7:9300},{6qrm9nU}{6qrm9nUiR1CCu5eqllmYWQ}{YCJhoNNDRveFTOzV4izAqw}{10.64.0.14}{10.64.0.14:9300},}, reason: zen-disco-receive(from master [master {AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300} committed version [6]])
[2017-02-28T07:38:39,318][INFO ][o.e.n.Node               ] [i-_yoLv] started
[2017-02-28T07:38:41,967][INFO ][o.e.c.s.ClusterService   ] [i-_yoLv] added {{rU-00ux}{rU-00uxFT8CJTNt-p2OgXA}{nC8LeRD2R9OKY5wh2-o-TQ}{10.64.2.18}{10.64.2.18:9300},}, reason: zen-disco-receive(from master [master {AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300} committed version [7]])
[2017-02-28T07:57:58,108][INFO ][o.e.c.s.ClusterService   ] [i-_yoLv] added {{_Ae2kjx}{_Ae2kjxpT_2MaDdOU5LzJA}{JP6dOlpUSfepcn20YomZEQ}{10.64.1.8}{10.64.1.8:9300},}, reason: zen-disco-receive(from master [master {AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300} committed version [8]])
[2017-02-28T07:58:05,024][INFO ][o.e.c.s.ClusterService   ] [i-_yoLv] removed {{rU-00ux}{rU-00uxFT8CJTNt-p2OgXA}{nC8LeRD2R9OKY5wh2-o-TQ}{10.64.2.18}{10.64.2.18:9300},}, reason: zen-disco-receive(from master [master {AmaxiMm}{AmaxiMmkSh-zbhjpvSb7FA}{JnM3jYhSQ9yxXg8N8wETEw}{10.64.1.6}{10.64.1.6:9300} committed version [9]])
```

The running POD:
```
(git)-[master] % kubectl get pod es-data-2407596567-3cg31 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"es-data-2407596567","uid":"ce15aaf8-fd88-11e6-a531-42010a84001d","apiVersion":"extensions","resourceVersion":"8369"}}
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      es-data; cpu request for init container sysctl'
    pod.alpha.kubernetes.io/init-container-statuses: '[{"name":"sysctl","state":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2017-02-28T07:37:50Z","finishedAt":"2017-02-28T07:37:50Z","containerID":"docker://d80835a0321de93ed3f492c6b74d2150d5930cb494acf956e83386457bb6fa53"}},"lastState":{},"ready":true,"restartCount":0,"image":"busybox","imageID":"docker://sha256:7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768","containerID":"docker://d80835a0321de93ed3f492c6b74d2150d5930cb494acf956e83386457bb6fa53"}]'
    pod.alpha.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{"requests":{"cpu":"100m"}},"volumeMounts":[{"name":"default-token-lz02t","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
    pod.beta.kubernetes.io/init-container-statuses: '[{"name":"sysctl","state":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2017-02-28T07:37:50Z","finishedAt":"2017-02-28T07:37:50Z","containerID":"docker://d80835a0321de93ed3f492c6b74d2150d5930cb494acf956e83386457bb6fa53"}},"lastState":{},"ready":true,"restartCount":0,"image":"busybox","imageID":"docker://sha256:7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768","containerID":"docker://d80835a0321de93ed3f492c6b74d2150d5930cb494acf956e83386457bb6fa53"}]'
    pod.beta.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{"requests":{"cpu":"100m"}},"volumeMounts":[{"name":"default-token-lz02t","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
  creationTimestamp: 2017-02-28T07:37:49Z
  generateName: es-data-2407596567-
  labels:
    component: elasticsearch
    pod-template-hash: "2407596567"
    role: data
  name: es-data-2407596567-3cg31
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: es-data-2407596567
    uid: ce15aaf8-fd88-11e6-a531-42010a84001d
  resourceVersion: "8437"
  selfLink: /api/v1/namespaces/default/pods/es-data-2407596567-3cg31
  uid: ce18c802-fd88-11e6-a531-42010a84001d
spec:
  containers:
  - env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CLUSTER_NAME
      value: myesdb
    - name: NODE_MASTER
      value: "false"
    - name: NODE_INGEST
      value: "false"
    - name: HTTP_ENABLE
      value: "false"
    - name: ES_JAVA_OPTS
      value: -Xms256m -Xmx256m
    image: quay.io/pires/docker-elasticsearch-kubernetes:5.2.0
    imagePullPolicy: Always
    name: es-data
    ports:
    - containerPort: 9300
      name: transport
      protocol: TCP
    resources:
      requests:
        cpu: 100m
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_RESOURCE
      privileged: false
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /data
      name: storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lz02t
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-es-test-cluster-1-default-pool-563942e3-bddv
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: storage
  - name: default-token-lz02t
    secret:
      defaultMode: 420
      secretName: default-token-lz02t
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-02-28T07:37:50Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-02-28T07:37:54Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-02-28T07:37:49Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9a7aeb890cae557a87997aad2f319a52a410a05f2e3c001df714c2cc4d531b3d
    image: quay.io/pires/docker-elasticsearch-kubernetes:5.2.0
    imageID: docker://sha256:35078b35686e39b5d1a5f98c921f704fca885af972dba14821a594578f15686e
    lastState: {}
    name: es-data
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2017-02-28T07:37:54Z
  hostIP: 10.132.0.2
  phase: Running
  podIP: 10.64.2.17
  startTime: 2017-02-28T07:37:49Z
```

**Comment by pires** [comment]
Thanks a ton! /cc @jimmidyson

**Comment by pires** [comment]
@hikhvar can we remove privileged from the init container as well?

**Comment by hikhvar** [comment]
As far as I know the `/proc` file system is not guarded by any Linux Capabilities. I tried the solution mentioned here: http://unix.stackexchange.com/questions/209244/which-linux-capability-do-i-need-in-order-to-write-to-proc-sys-vm-drop-caches but that doesn't work for my setup.

**Comment by pires** [comment]
True, thanks!

**Pull request merged**
