### PR TITLE
Add sample of using StatefulSet for data pods

### PR DESCRIPTION
**Pull request by wfhartford**
See conversation in #74

### CODE REVIEW

**Comment by pires** [comment]
I'll be extremely busy over the next few days but I will look into this soon. Thank you!

**Comment by hikhvar** [comment]
Tested it. Looks really good.

**Comment by pires** [comment]
Sweet, thanks a ton!

**Comment by hiscal2015** [comment]
@wfhartford @pires Wonderful sample! And, may I know is it necessary for master nodes? I'm new to elasticsearch and I don't know whether persistent storage is needed for master or client nodes, thanks.

**Comment by pires** [comment]
@hiscal2015 there are no special storage requirements for master and client nodes.

**Pull request merged**
