### PR TITLE
adding curator for cleanup of indices

### PR DESCRIPTION
**Pull request by puja108**
Adding Curator as add-on in form of a Scheduled Job, which runs once a day and cleans up old indices. The Scheduled Job is configured through a Config Map object.

### CODE REVIEW

**Comment by puja108** [comment]
@pires this should work with your ES service, want me to add sth to the readme for it?

**Comment by pires** [comment]
Yes, documentation on how to enable/disable this is a must.

**Comment by puja108** [comment]
cool, will work on it

**Comment by puja108** [comment]
added the docs

RFR @pires

**Comment by pires** [comment]
Cool, thanks a ton!

**Pull request merged**
